---
version: '3.8'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: flashcard-microservice
      POSTGRES_PASSWORD: flashcard-microservice
    ports:
      - 5432:5432
    volumes:
      - flashcard-microservice-data:/var/lib/postgresql/data

volumes:
  flashcard-microservice-data:
